#Author Groot314
#Modification from 1.1.1 to 1.2 done by Zordain

name: Troll
main: me.gamerman314.Troll.Troll
version: 1.3
permissions:
  troll.trolol:
    description: Allows you to call another player a trololol.
    default: true
  troll.kick:
    description: Allows you to troll kick a player.
    default: OP 
  troll.trolled:
    description: Allows you to tell the server that you trolled someone.
    default: true
  troll.trolled.all:
    decripton: Allows you to tell the server that you've trolled everyone.
    default: true
  troll.facepalm:
    decripton: Allows you to say you facepalm.
    default: true
  troll.barrelroll:
    decripton: Allows you to do barrel rolls.
    default: true
  troll.superTroll:
    dectription: Allows you to say your a Super Troll
    default: true

commands:
  trolled:
    description: Tell the server that you trolled someone.
    usage: /trolled <player>
  trolledall:
    description: Tell the server that you trolled everyone.
    usage: /trolledall
  troll:
    description: Tell the Server who is a Troll.
    usage: /troll <Player>
  trollkick:
    description: Troll kicks a Player.
    usage: /trollkick <Player>
  facepalm:
    description: Tells the server that you facepalmed.
    usage: /facepalm
  barrelroll:
    description: Do a barrel roll.
    usage: /barrelroll <Player>
  supertroll:
    description: Tells the server your a Super Troll
    usage: /superTroll <player>